AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Audio Generation Lambda Function for Podcasto with Google TTS Integration

Globals:
  Function:
    Timeout: 900  # 15 minutes for audio generation processing (SQS visibility timeout is 960s)
    MemorySize: 2048  # Increased memory for audio processing
    Runtime: python3.12

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  ExistingSQSQueueUrl:
    Type: String
    Default: 'https://sqs.us-east-1.amazonaws.com/638520701769/podcast-processing-queue'
    Description: 'URL of the existing SQS queue used by telegram-lambda'
  
  SecretsManagerName:
    Type: String
    Default: 'podcasto-secrets-dev'
    Description: 'Name of the Secrets Manager secret containing API keys'
  
  ApiBaseUrl:
    Type: String
    Default: 'https://your-podcasto-app.vercel.app'
    Description: 'Base URL of the Next.js application for callbacks'
  
  LambdaCallbackSecret:
    Type: String
    Default: 'a5a90267-4023-4c80-980b-47166d9d8d6e'
    Description: 'Secret for authenticating Lambda callbacks to Next.js API'
  
Resources:
  AudioGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'podcasto-audio-generation-${Environment}'
      Description: 'Audio generation with Google TTS and multi-speaker support'
      CodeUri: src/
      Handler: handlers.audio_generation_handler.lambda_handler
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          SQS_QUEUE_URL: !Ref ExistingSQSQueueUrl
          S3_BUCKET_NAME: 'podcasto-podcasts'
          SUPABASE_URL: !Sub '{{resolve:secretsmanager:${SecretsManagerName}:SecretString:SUPABASE_URL}}'
          SUPABASE_SERVICE_KEY: !Sub '{{resolve:secretsmanager:${SecretsManagerName}:SecretString:SUPABASE_SERVICE_KEY}}'
          GEMINI_API_KEY: !Sub '{{resolve:secretsmanager:${SecretsManagerName}:SecretString:GEMINI_API_KEY}}'
          API_BASE_URL: !Ref ApiBaseUrl
          LAMBDA_CALLBACK_SECRET: !Ref LambdaCallbackSecret
          LOG_LEVEL: 'INFO'
          LAST_UPDATED: '2025-06-13-07:30'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:podcast-processing-queue'
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:podcast-processing-queue'
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource: 
                - 'arn:aws:s3:::podcasto-podcasts'
                - 'arn:aws:s3:::podcasto-podcasts/*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 
                - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretsManagerName}*'

Outputs:
  AudioGenerationFunctionArn:
    Description: 'ARN of the Audio Generation Lambda Function'
    Value: !GetAtt AudioGenerationFunction.Arn
    Export:
      Name: !Sub '${Environment}-AudioGenerationFunctionArn'
      
  ExistingSQSQueueUrl:
    Description: 'URL of the existing SQS Queue used for podcast processing'
    Value: !Ref ExistingSQSQueueUrl
    Export:
      Name: !Sub '${Environment}-ExistingSQSQueueUrl' 