version = 0.1

[default]
[default.local_invoke]
[default.local_invoke.parameters]
parameter_overrides = [
  "GeminiApiKey=${GEMINI_API_KEY}",
  "OpenAiApiKey=${OPENAI_API_KEY}",
  "S3BucketName=${S3_BUCKET_NAME}",
  "SupabaseUrl=${SUPABASE_URL}",
  "SupabaseKey=${SUPABASE_KEY}",
  "SQSQueueArn=${SQS_QUEUE_ARN}"
]

[default.deploy.parameters]
stack_name = "podcasto-podcast-generator-v2"
resolve_s3 = true
s3_prefix = "podcasto-podcast-generator-v2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"${S3_BUCKET_NAME}\" SQSQueueArn=\"${SQS_QUEUE_ARN}\" SupabaseUrl=\"${SUPABASE_URL}\" SupabaseKey=\"${SUPABASE_KEY}\""
image_repositories = ["PodcastGeneratorFunction=638520701769.dkr.ecr.us-east-1.amazonaws.com/podcastopodcastgenerator05ec9e89/podcastgeneratorfunction50159cadrepo"] 