AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TelegramCollector:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.10
    Properties:
      CodeUri: .
      Handler: src.lambda_handler.lambda_handler
      Runtime: python3.12
      Timeout: 300
      MemorySize: 256
      Layers:
        - arn:aws:lambda:us-east-1:638520701769:layer:podcasto-shared-layer-dev:3
      Environment:
        Variables:
          TELEGRAM_API_ID: !Ref TelegramApiId
          TELEGRAM_API_HASH: !Ref TelegramApiHash
          TELEGRAM_SESSION: !Ref TelegramSession
          S3_BUCKET_NAME: !Ref S3BucketName
          SQS_QUEUE_URL: !Ref SQSQueueUrl
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
          API_ENDPOINT: !Ref ApiEndpoint
          INTERNAL_API_KEY: !Ref InternalApiKey
          LOG_LEVEL: DEBUG
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: "*"

Parameters:
  TelegramApiId:
    Type: String
    Description: Telegram API ID
    NoEcho: true

  TelegramApiHash:
    Type: String
    Description: Telegram API Hash
    NoEcho: true

  TelegramSession:
    Type: String
    Description: Telegram Session String
    NoEcho: true

  S3BucketName:
    Type: String
    Description: S3 Bucket Name for storing messages
    Default: ""
    
  SQSQueueUrl:
    Type: String
    Description: URL of the SQS queue for podcast processing
    Default: ""
    
  SupabaseUrl:
    Type: String
    Description: Supabase URL
    Default: ""
    NoEcho: true
    
  SupabaseKey:
    Type: String
    Description: Supabase API Key
    Default: ""
    NoEcho: true
    
  ApiEndpoint:
    Type: String
    Description: Base URL for API endpoint (e.g., https://yourapp.vercel.app)
    Default: ""
    
  InternalApiKey:
    Type: String
    Description: Internal API key for authentication
    Default: ""
    NoEcho: true 