name: Deploy Lambdas to Production

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DEPLOY TO PRODUCTION" to confirm'
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  ENVIRONMENT: prod

jobs:
  # Safety check: Validate confirmation input
  validate-confirmation:
    name: Validate Deployment Confirmation
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "DEPLOY TO PRODUCTION" ]; then
            echo "❌ Deployment cancelled: Confirmation text does not match"
            echo "Expected: DEPLOY TO PRODUCTION"
            echo "Received: ${{ github.event.inputs.confirmation }}"
            exit 1
          fi
          echo "✅ Deployment confirmed"

  # Job 1: Deploy shared layer to production
  deploy-shared-layer:
    name: Deploy Shared Layer to Production
    runs-on: ubuntu-latest
    needs: validate-confirmation
    outputs:
      layer_arn: ${{ steps.get-layer-arn.outputs.arn }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build shared layer
        working-directory: Lambda/shared-layer
        run: sam build

      - name: Deploy shared layer to PRODUCTION
        working-directory: Lambda/shared-layer
        run: |
          echo "🚀 Deploying to PRODUCTION environment..."
          sam deploy \
            --stack-name podcasto-shared-layer-${{ env.ENVIRONMENT }} \
            --no-confirm-changeset \
            --parameter-overrides "Environment=${{ env.ENVIRONMENT }}" \
            --capabilities CAPABILITY_IAM \
            --resolve-s3

      - name: Get new layer ARN
        id: get-layer-arn
        run: |
          LAYER_ARN=$(aws cloudformation describe-stacks \
            --stack-name podcasto-shared-layer-${{ env.ENVIRONMENT }} \
            --query 'Stacks[0].Outputs[?OutputKey==`SharedLayerArn`].OutputValue' \
            --output text)
          echo "Production layer ARN: $LAYER_ARN"
          echo "arn=$LAYER_ARN" >> $GITHUB_OUTPUT

  # Job 2: Deploy production Lambda functions (build + deploy full Lambda code)
  deploy-lambdas:
    name: Deploy Production Lambda Functions
    runs-on: ubuntu-latest
    needs: deploy-shared-layer
    strategy:
      matrix:
        include:
          - lambda_name: telegram-lambda
            stack_name: podcasto-telegram-collector-v2-prod
            function_name: podcasto-telegram-collector-v2-prod-TelegramCollector
          - lambda_name: script-preprocessor-lambda
            stack_name: podcasto-script-preprocessor-prod
            function_name: podcasto-script-preprocessor-prod
          - lambda_name: audio-generation-lambda
            stack_name: podcasto-audio-generation-prod
            function_name: podcasto-audio-generation-prod
      fail-fast: true  # Stop immediately if any Lambda fails in production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build ${{ matrix.lambda_name }}
        working-directory: Lambda/${{ matrix.lambda_name }}
        run: sam build

      - name: Deploy ${{ matrix.lambda_name }} to PRODUCTION
        working-directory: Lambda/${{ matrix.lambda_name }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
        run: |
          echo "🚀 Deploying ${{ matrix.lambda_name }} to PRODUCTION..."
          sam deploy \
            --stack-name ${{ matrix.stack_name }} \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --resolve-s3

      - name: Wait for ${{ matrix.function_name }} to be ready
        run: |
          echo "Waiting for ${{ matrix.function_name }} to finish updating..."
          aws lambda wait function-updated-v2 --function-name ${{ matrix.function_name }}
          echo "✅ ${{ matrix.function_name }} deployed successfully to PRODUCTION"

  # Job 3: Verify production deployment
  verify-deployment:
    name: Verify Production Deployment
    runs-on: ubuntu-latest
    needs: deploy-lambdas

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify production Lambda configurations
        run: |
          echo "Verifying PRODUCTION Lambdas..."

          # Check all 3 Lambda functions
          for lambda in \
            podcasto-telegram-collector-v2-prod-TelegramCollector \
            podcasto-script-preprocessor-prod \
            podcasto-audio-generation-prod; do

            echo "Checking $lambda..."
            CONFIG=$(aws lambda get-function-configuration --function-name $lambda)
            STATE=$(echo $CONFIG | jq -r '.State')
            LAST_UPDATE_STATUS=$(echo $CONFIG | jq -r '.LastUpdateStatus')
            LAST_MODIFIED=$(echo $CONFIG | jq -r '.LastModified')

            echo "  State: $STATE"
            echo "  Last Update Status: $LAST_UPDATE_STATUS"
            echo "  Last Modified: $LAST_MODIFIED"

            if [ "$STATE" != "Active" ] || [ "$LAST_UPDATE_STATUS" != "Successful" ]; then
              echo "❌ PRODUCTION $lambda deployment failed!"
              exit 1
            fi
            echo "✅ $lambda is healthy"
          done

          echo ""
          echo "🎉 All PRODUCTION Lambdas deployed successfully!"
          echo "Deployment commit: ${{ github.sha }}"
          echo "Deployed by: ${{ github.actor }}"
